# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [released]

jobs:
  extract-version:
    name: Extract Keycloak version from release tag
    runs-on: ubuntu-latest
    outputs:
      kc-version: ${{ steps.extract.outputs.kc_version }}
    steps:
      - name: Extract Keycloak version from release tag
        id: extract
        run: |
          # Assuming the release tag is in the format "vXX.X.XX" or "vXX.XX.XX"
          RELEASE_TAG=${{ github.event.release.tag_name }}
          # Extract the version part from the release tag
          if [[ "$RELEASE_TAG" =~ ^v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            echo "::set-output name=kc_version::${BASH_REMATCH[1]}"
          else
            echo "Invalid release tag format: $RELEASE_TAG"
            exit 1
          fi

  build:
    needs: extract-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Set version
        run: mvn versions:set -DnewVersion=KC${{ needs.extract-version.outputs.kc-version }}
      - name: Build with Maven
        run: mvn -Dkeycloak.version=${{ needs.extract-version.outputs.kc-version }} -B package --file pom.xml
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/keycloak-2fa-email-authenticator*
          name: Keycloak 2FA Email Authenticator ${{ github.event.release.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
