name: 📅 Schedule Workflow Dispatch
on:
  push:
  pull_request:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs:
      date:
        description: 'Date to run the workflow'
        required: true
        type: string
        default: 'in 1 minute'
concurrency:
  group: schedule${{ github.event.inputs.date }}
  cancel-in-progress: true

jobs:
  schedule:
    name: 📅 Schedule
    runs-on: ubuntu-latest
    steps:
      - uses: austenstone/schedule@v1.3
        with:
          github-token: ${{ secrets.TOKEN }}
          date: ${{ github.event.inputs.date }}
          workflow: 'test.yml'
          timezone: 'Europe/Madrid' # US/Central, US/Pacific
          inputs: '{"app": "test:1.2.3"}'
          wait-ms: 45000
