name: Test
on:
  workflow_dispatch:
    inputs:
      app:
        description: 'App name and version (myapp:1.2.3)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: echo Deploying, ${{ github.event.inputs.app }}!
